# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-17 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=128)),
                ('onderwerp', models.CharField(max_length=256)),
                ('begintijd', models.TimeField()),
                ('eindtijd', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inleesdatum', models.DateTimeField(default=django.utils.timezone.now)),
                ('naam', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.DataSet'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
