# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_agendaitem_tijdsduur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='google',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataset',
            name='importfile',
            field=models.FileField(null=True, upload_to='uploads/%d/%m/%Y/'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='outlook',
            field=models.BooleanField(default=False),
        ),
    ]
